# Generated by Django 4.1.2 on 2022-10-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slackUsername', models.CharField(max_length=30)),
                ('backend', models.BooleanField(default=True)),
                ('age', models.IntegerField()),
                ('bio', models.CharField(max_length=200)),
            ],
        ),
    ]
